### PR TITLE
scripts/BSB-LAN_evaluate_datalogs/ added

### PR DESCRIPTION
**Pull request by DE-cr**
sample code to show how BSB-LAN's /D datalogs could be processed using pandas/python, including conversion to pivoted *.csv and some plot ideas

with plot examples

feel free to reject this PR and just link to my fork's branch from the BSB-LAN docs ... or not :)

### CODE REVIEW

**Comment by fredlcore** [comment]
I rather link to your repo, because I wouldn't be able to answer any questions that may arise from that, as I have hardly any knowledge in python, nor in such kind of data processing. Which link should I use?

**Comment by DE-cr** [comment]
How about linking here?:
https://github.com/DE-cr/BSB-LAN/tree/BSB-LAN_evaluate_datalogs/BSB_LAN/scripts/BSB-LAN_evaluate_datalogs

**Comment by fredlcore** [comment]
Sure, maybe you can add a small README.md, explaining what this is and how to use it? But up to you...

**Comment by fredlcore** [comment]
[Added](https://github.com/fredlcore/BSB-LAN/wiki/Links-to-BSB%E2%80%93LAN%E2%80%93related-projects)

**Comment by DE-cr** [comment]
You might want to drop the "several". So far it's only one script containing a few examples.

**Comment by fredlcore** [comment]
Done.

**Comment by DE-cr** [comment]
> Sure, maybe you can add a small README.md, explaining what this is and how to use it? But up to you...

[Done.](https://github.com/DE-cr/BSB-LAN/tree/BSB-LAN_evaluate_datalogs/BSB_LAN/scripts/BSB-LAN_evaluate_datalogs) (Good idea, thank you! I hadn't thought of providing a README.md in a sub-directory.)

**Comment by fredlcore** [comment]
Looks great, thanks!

**Pull request closed without merging**
