### PR TITLE
Dynamic URL changing

### PR DESCRIPTION
**Pull request by dukess**

### CODE REVIEW

**Comment by fredlcore** [comment]
Great idea, thanks a lot!

**Comment by 1coderookie** [comment]
Sorry guys, I don't get it - what is this function for? How & where should I mention it within the manual?

**Comment by fredlcore** [comment]
No need to mention it in the manual, it just automatically updates the link to the sensors in the menu to refer to the correct category number, so that each time (hopefully no more ;)!) a new category is added, the sensor category is updated automatically in the menu.

**Comment by 1coderookie** [comment]
Ah ok - well that's cool though! :)

**Comment by fredlcore** [comment]
Especially since I always forget that I need to change something there as well ;)...

**Pull request merged**
