### PR TITLE
Stop serving client that is already gone

### PR DESCRIPTION
**Pull request by DE-cr**
...at least for potentially long lasting actions, e.g. /D or /K24.
This avoids unnecessarily blocking bsb-lan for other tasks (including new client requests).

Succesfully tested on ESP32 with wifi connection, using the url commands given above.
I consider this ready for merging.

### CODE REVIEW

**Comment by DE-cr** [comment]
P.s. now also addressing /QD handling. (Tested on my system.)

**Comment by fredlcore** [comment]
Great idea, thanks! Does this also mean that you can abort let's say a long query of parameters (such as /0-9999) by hitting the "Stop" button on the browser and start a new query right after? Because that has often confused users who were wondering why BSB-LAN was still not responding for minutes until the query in the background was completed.

**Comment by DE-cr** [comment]
Yes, tested right now. :)

**Comment by DE-cr** [comment]
Btw, I've done my testing by calling the url commands that usually take a long time, then immediately going back to the previous page in the browser (alt + left), which cancels the client connection and creates a new one.

**Comment by fredlcore** [comment]
Great, that's really helpful!

**Pull request merged**
